### ISSUE TITLE
Horrible performance on VSCODE 2019, july update.

### ISSUE THREAD

**Issue by coderguy1777** [Strum355/mcshader-lsp#20]
Extension causes alot of lag within a workspace with the extension installed with it lagging  a whole system even.

**Comment by Strum355** [comment]
Is this a workspace with glsl files?

**Comment by coderguy1777** [comment]
Not really, I had like 2 glsl files in my workspace, and VSCODE had an alert appear saying that the extension was responsible for extreme performance slow downs in VSCODE itself.

**Comment by Strum355** [comment]
youre probably better off disabling the extension for the workspace. Not sure why it gave that alert given that the actual language server runs in a seperate process and all it does is inter-process communication. This hasnt been updated in quite a while though, its currently undergoing a major rewrite. 
Im curious why youre using this extension btw, i couldnt find you in any of the Minecraft Shader discord servers.

**Comment by coderguy1777** [comment]
Thought I might use it to make writing my game engine easier and implementing engine shaders, and right now just setting up my camera shader to work right, thought this extension might make it easier.

**Comment by Strum355** [comment]
This extension is specifically geared to Minecraft Shaders, with its peculiarities and specific implementation differences that are non-standard and this extension (currently) expects you to be working in the Minecraft Shaders workspace scenario. I feel like it mightnt be what youre looking for im afraid

You may have better luck with one of these
https://marketplace.visualstudio.com/items?itemName=CADENAS.vscode-glsllint
https://marketplace.visualstudio.com/items?itemName=majicDave.vscode-shaderc
https://marketplace.visualstudio.com/items?itemName=mrjjot.vscode-glsl-linter
https://marketplace.visualstudio.com/items?itemName=evanw.glslx-vscode
