### ISSUE TITLE
Problems with Windows and drive letters

### ISSUE THREAD

**Issue by DethRaid** [Strum355/mcshader-lsp#21]
I have my `.minecraft` folder on my E drive. The extension gave me the following error:

```
Shaderpacks path may not be correct. Current file is in '/e%3A/Documents/MultiMC/instances/1.13.2/.minecraft/shaderpacks/Sprout/shaders/composite.fsh' but the path is set to 'E:/Documents/MultiMC/instances/1.13.2/.minecraft/shaderpacks'
```

Apparently something translates the file path to URL encoding, but not the shaderpack folder path from the settings

**Comment by DethRaid** [comment]
Manually typing in the URL encoded filepath worked, but it'd be nice if this extension supported windows drive letters

**Comment by Strum355** [comment]
Yup thats a known issue, we're in the middle of a complete rewrite so that should be addressed in the upcoming update

**Comment by DethRaid** [comment]
Yay

**Comment by Strum355** [comment]
This shouldnt be an issue anymore, gonna close it
