### ISSUE TITLE
Error checking not working

### ISSUE THREAD

**Issue by LowSpecCorgi** [Strum355/mcshader-lsp#24]
It seems that the extension is reporting errors on lines without anything, Minecraft says **invalid program**, but the extension does not tell where the errors actually are:
![image](https://user-images.githubusercontent.com/59167551/85844999-793bd680-b79b-11ea-82b2-63c00a06cb61.png)

**Comment by Strum355** [comment]
This is a known issue with the current public release. It is currently being rewritten from the ground up and should be considerably more reliable when the time comes :)
