### ISSUE TITLE
[Suggestion] Use %appdata%/.minecraft/shaderpacks as default shaderpack location

### ISSUE THREAD

**Issue by xieve** [Strum355/mcshader-lsp#25]
Currently, you have to fill in the path, even if you have a standard Minecraft installation. I guess this would save new users some time.

**Comment by xieve** [comment]
For Linux, it'd be `$HOME/.minecraft`, obviously.

**Comment by Strum355** [comment]
This is no longer an issue, so Im going to close this :slightly_smiling_face:
