### ISSUE TITLE
Error while including files in some situation

### ISSUE THREAD

**Issue by GeForceLegend** [Strum355/mcshader-lsp#29]
While a file is included by using "/../shaders/", all files included in this file could not get included while linting.
The red line on the bottom of test1.glsl reports "OpenGL does not allow #include directives", maybe something will get lost while a file is included by "/../shaders/"?
Include a file with path "/../shaders/" is important in nether and the end shader. Please fix this as soon as possible.
![20210221090024](https://user-images.githubusercontent.com/41003546/108612390-5d203000-7423-11eb-816d-64950380945f.png)

**Comment by Strum355** [comment]
You shouldnt use /../ as an import. Last i remember, its invalid when the shader is in a zip file, it only works if unzipped. 
Im not aware of ever having to do /../ for includes. Does / not start from the top shaders folder already? I will double check with some people in the shader server 🙂

**Comment by Strum355** [comment]
Ive been informed that includes starting with / start in the `shaders` folder, so there should be no need to ever import with /../ 🙂 hope that helps
