### ISSUE TITLE
The extension crashes when I enter an include file

### ISSUE THREAD

**Issue by Jessie-LC** [Strum355/mcshader-lsp#40]
It appears to happen anytime I enter any include within an include.

[log.txt](https://github.com/Strum355/mcshader-lsp/files/8548846/log.txt)
[NV.zip](https://drive.google.com/file/d/1zW4HpwQoF-cm9pfZGW2jdNFr9_44ZsoZ/view?usp=sharing)

**Comment by Strum355** [comment]
Should be fixed by https://github.com/Strum355/mcshader-lsp/commit/3b568ea08759e10a9cef0f97e44673dc3b91cb40, thx for the report and shaderzip :+1:
