### ISSUE TITLE
Does not linting compute shader with _a to _z suffix

### ISSUE THREAD

**Issue by GeForceLegend** [Strum355/mcshader-lsp#45]
Optifine allows shaderpacks using suffix from _a to _z to attach at most 27 compute shader per program, but this extension only linting compute shader without suffix (for exmaple, composite.csh will get linted, but composite_a.csh will not).

Reference in optifine document:
**They are named like the program with optional suffix, for example "composite.csh", "composite_a.csh" ... "composite_z.csh".**

**Comment by Strum355** [comment]
Thanks for the report, that is indeed an oversight. Out of curiosity, have you noticed any other issues with linting compute shaders? I have no experience with them, so I dont know what to expect

**Comment by GeForceLegend** [comment]
Everything works well so far, excepting when restarting language server by command line, included files in compute shader will act like OpenGL version is not specified, saying "OpenGL does not allow #include directives" when there are #include in included files, but turns fine after saving once

**Comment by GeForceLegend** [comment]
Found that "OpenGL does not allow #include directives" is caused by my included file extension for compute shaders programs is `.comp` but not `.glsl` or `.inc`. Sorry about making you confused, now the only issue is the compute shader linting with suffixes, which i tried to solve in my pull request.
